export const boards = [
  // A
  [
    [
      { color: "grey", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "star", marked: false },
      { color: "star", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false, star: true },
      { color: "orange", marked: false }
    ],
    [
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false, star: true },
      { color: "orange", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "yellow", marked: false }
    ],
    [
      { color: "green", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "white", marked: true },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "red", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "green", marked: false, star: true }
    ],
    [
      { color: "orange", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "yellow", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false }
    ]
  ],
  // B
  [
    [
      { color: "blue", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "yellow", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "red", marked: false, star: true },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false, star: true }
    ],
    [
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "white", marked: true },
      { color: "blue", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false, star: true },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "red", marked: false, star: true },
      { color: "yellow", marked: false }
    ]
  ],
  //  D
  [
    [
      { color: "grey", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false, star: true },
      { color: "grey", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "green", marked: false, star: true },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "white", marked: true },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false, star: true }
    ],
    [
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "red", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false }
    ],
    [
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false, star: true }
    ]
  ],
  //  E
  [
    [
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "blue", marked: false, star: true },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false, star: true }
    ],
    [
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "white", marked: true },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "yellow", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false }
    ],
    [
      { color: "yellow", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false, star: true },
      { color: "red", marked: false },
      { color: "red", marked: false }
    ]
  ],
  [
    [
      { color: "green", marked: false, star: true },
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false, star: true }
    ],
    [
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "grey", marked: false, star: true },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "orange", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "white", marked: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "yellow", marked: false },
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false, star: true }
    ],
    [
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "grey", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "red", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "grey", marked: false }
    ]
  ],
  //  G
  [
    [
      { color: "red", marked: false },
      { color: "red", marked: false, star: true },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "yellow", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "blue", marked: false, star: true },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "blue", marked: false, star: true }
    ],
    [
      { color: "blue", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "white", marked: true },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "green", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "green", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "black", marked: false },
      { color: "orange", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "red", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "yellow", marked: false }
    ]
  ],
  //  H
  [
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "yellow", marked: false }
    ],
    [
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "blue", marked: false, star: true },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false, star: true },
      { color: "red", marked: false },
      { color: "red", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "orange", marked: false },
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "yellow", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "white", marked: true },
      { color: "red", marked: false },
      { color: "orange", marked: false },
      { color: "blue", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "blue", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "yellow", marked: false },
      { color: "green", marked: false, star: true },
      { color: "green", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false, star: true },
      { color: "grey", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "blue", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "grey", marked: false }
    ]
  ],
  [
    [
      { color: "red", marked: false },
      { color: "red", marked: false, star: true },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "grey", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "blue", marked: false }
    ],
    [
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "blue", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false, star: true },
      { color: "red", marked: false },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "orange", marked: false },
      { color: "green", marked: false },
      { color: "blue", marked: false }
    ],
    [
      { color: "yellow", marked: false, star: true },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "yellow", marked: false },
      { color: "yellow", marked: false },
      { color: "white", marked: true },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "black", marked: false },
      { color: "black", marked: false },
      { color: "grey", marked: false }
    ],
    [
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "blue", marked: false, star: true },
      { color: "grey", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false, star: true }
    ],
    [
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "blue", marked: false },
      { color: "blue", marked: false },
      { color: "orange", marked: false },
      { color: "black", marked: false },
      { color: "red", marked: false },
      { color: "red", marked: false },
      { color: "yellow", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false }
    ],
    [
      { color: "yellow", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "grey", marked: false },
      { color: "orange", marked: false, star: true },
      { color: "black", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false, star: true },
      { color: "yellow", marked: false },
      { color: "green", marked: false },
      { color: "red", marked: false },
      { color: "grey", marked: false }
    ],
    [
      { color: "green", marked: false },
      { color: "green", marked: false, star: true },
      { color: "green", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "orange", marked: false },
      { color: "green", marked: false },
      { color: "green", marked: false },
      { color: "yellow", marked: false },
      { color: "green", marked: false, star: true },
      { color: "red", marked: false }
    ]
  ]
];
